### ISSUE TITLE
[ADDON] - KNative: Deletion of the addon once it has been deployed results in ArgoCD sync error

### ISSUE THREAD

**Issue by julianxhokaxhiu** [nearform/k8s-kurated-addons#17]
### Issue Type

Bug

### Description

When attempting to delete the KNative addon ( by excluding it from the list of `app-of-apps.yaml` once it has been already applied, results in ArgoCD erroring that the `knative-eventing` is not found, and therefore it can't continue with the namespace deletion.

```
Unable to delete application resources: applications.argoproj.io "knative-operator" not found
Warning  StatusRefreshed     14m   argocd-application-controller  Unable to delete application resources: applications.argoproj.io "knative-eventing" not found
```
  
There seems to be a race condition between the `knative-operator` and ArgoCD trying to delete the same namespace, and apparently, the operator deletes it before Argo, causing, therefore, this sync error.

### Detailed steps

```bash
1. Run `make ci`
2. Run `KKA_AOA_EXCLUDE_KNATIVE=true make ci`
3. Proof it
```

**Comment by mile-misan** [comment]
PR: https://github.com/nearform/k8s-kurated-addons/pull/28
