### ISSUE TITLE
[ADDON] - Open Telemetry

### ISSUE THREAD

**Issue by julianxhokaxhiu** [nearform/k8s-kurated-addons#22]
### Issue Type

Enhancement

### Description

**The Context:**
The stack currently offers Prometheus and Grafana as a monitoring solution, but the industry is going for [Open Telemetry](https://opentelemetry.io/) as a standard. Would be valuable to have this component as part of the stack to ensure developers can easily integrate their apps as many frameworks provide now an OTLP exporter out of the box.

**The Solution:**
Integrate the [Open Telemetry](https://opentelemetry.io/) stack as an addon and ensure it doesn't conflict with the Prometheus Operator. Additionally, an integration of Prometheus with Open Telemetry that works out of the box is a plus.

**The Alternatives:**
None considered.

**Comment by ilchebedelovski** [comment]
Once the OpenTelemetry addons are configured correctly based on the requirements that we have, the next challenge is deploying a tool that will visualize the logs and metrics. In the next section I am going to explain the Collector, Operator and Grafana Loki (as an exporter).

- OpenTelemetry Collector - OpenTelemetry collector consists of three main components:
	- Receivers - are used to get data into the collector. You can use the receivers to configure ports and formats the collector can take data in. You can receive data in multiple formats. It has a default OTLP format, but you can receive data in other popular open-source formats like Jaeger or Prometheus.
	- Processors - are used to do any processing required on the collected data, like data massaging, data manipulation, or any change in the data as it flows through the collector.
	- Exporters - are used to export data to an observability backend like SigNoz. You can send out data in multiple data formats. You can send different telemetry signals to different backend analysis tools.

- OpenTelemetry Operator - the OpenTelemetry Operator is an operator written by the OpenTelemetry community and aims to manage and simplify the way we incorporate observability into our system. One of the first challenges is the complexity of deploying auto instrumentation. Modern applications are packaged in container images. Adding instrumentation to our code requires modifying our business logic by adding instrumentation logic and rebuilding the image. Deploying the OpenTelemetry collector in Kubernetes relies on a pipeline definition stored in a config map. The major disadvantage is that any updates on our pipeline require restarting all the pods of our OpenTelemetry Collector. In the case of Kubernetes, the Operator simplifies a large part of managing telemetry data, like the deployment of the architecture of our collectors. 

- Exporting logs to visualizer like Grafana Loki
	- Loki is a horizontally scalable, highly available, multi-tenant log aggregation system. Loki has the ability to collect aggregated logs from the already deployed collector (in our case OpenTelemetry Collector).
	- In the OpenTelemetry Collector configuration, Loki needs to be configured as an exporter, for example:
	```
	exporters:
	  logging:
	    logLevel: debug

	  loki:
	    endpoint: "http://localhost:3100/loki/api/v1/push"
	```
	- Then in the Grafana Loki a new data source needs to be created for fetching the logs from the exporter.

**Comment by julianxhokaxhiu** [comment]
As far as I can understand from this, I'd consider therefore deploying both the OTLP Collector AND Operator, and through the operator configure the collector to export the logs to Loki.

No need to be done on this Issue though, but on the one that will introduce Loki ( see #37 ).

Thanks for the documentation, extremely helpful to understand the next steps.
