### ISSUE TITLE
PRs should have a status check to disable merge if integration tests are failing

### ISSUE THREAD

**Issue by LucaLanziani** [nearform/k8s-kurated-addons#73]
It's possible to Add github actions to the status check for protected brances, in this case we have `main` as a protected branch but we only need one approval to merge PRs

**Comment by zimny** [comment]
In other words, it must be prohibited to merge a branch if some checks are running or are failed.

**Comment by fabiolrodriguez** [comment]
Now Semantic PR and Lint & format checks being required.
